# 开发环境

# mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://107.172.180.188:3306/web-demo?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: normal
    password: AdTime06@17

